name: Test
"on":
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # tag=v3
      - uses: actions/setup-node@v3 # tag=v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm t
